# Generated by Django 3.2.3 on 2023-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
