# Generated by Django 3.2.3 on 2023-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_auto_20230930_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='asignaturas',
            field=models.ManyToManyField(to='course_management.Asignatura'),
        ),
    ]
